// Liste des pays : Afrique complète (marché principal) + principaux pays
// du reste du monde (diaspora, partenaires commerciaux). Le drapeau n'est
// pas stocké en dur : il est généré à partir du code ISO2, ce qui évite
// toute erreur de copier-coller d'emoji.
export function drapeau(iso) {
  return iso
    .toUpperCase()
    .replace(/./g, (c) => String.fromCodePoint(127397 + c.charCodeAt(0)));
}

export const PAYS = [
  // Afrique
  { iso: "DZ", nom: "Algérie", indicatif: "+213" },
  { iso: "AO", nom: "Angola", indicatif: "+244" },
  { iso: "BJ", nom: "Bénin", indicatif: "+229" },
  { iso: "BW", nom: "Botswana", indicatif: "+267" },
  { iso: "BF", nom: "Burkina Faso", indicatif: "+226" },
  { iso: "BI", nom: "Burundi", indicatif: "+257" },
  { iso: "CV", nom: "Cap-Vert", indicatif: "+238" },
  { iso: "CM", nom: "Cameroun", indicatif: "+237" },
  { iso: "CF", nom: "République centrafricaine", indicatif: "+236" },
  { iso: "TD", nom: "Tchad", indicatif: "+235" },
  { iso: "KM", nom: "Comores", indicatif: "+269" },
  { iso: "CG", nom: "Congo", indicatif: "+242" },
  { iso: "CD", nom: "RD Congo", indicatif: "+243" },
  { iso: "CI", nom: "Côte d'Ivoire", indicatif: "+225" },
  { iso: "DJ", nom: "Djibouti", indicatif: "+253" },
  { iso: "EG", nom: "Égypte", indicatif: "+20" },
  { iso: "GQ", nom: "Guinée équatoriale", indicatif: "+240" },
  { iso: "ER", nom: "Érythrée", indicatif: "+291" },
  { iso: "SZ", nom: "Eswatini", indicatif: "+268" },
  { iso: "ET", nom: "Éthiopie", indicatif: "+251" },
  { iso: "GA", nom: "Gabon", indicatif: "+241" },
  { iso: "GM", nom: "Gambie", indicatif: "+220" },
  { iso: "GH", nom: "Ghana", indicatif: "+233" },
  { iso: "GN", nom: "Guinée", indicatif: "+224" },
  { iso: "GW", nom: "Guinée-Bissau", indicatif: "+245" },
  { iso: "KE", nom: "Kenya", indicatif: "+254" },
  { iso: "LS", nom: "Lesotho", indicatif: "+266" },
  { iso: "LR", nom: "Liberia", indicatif: "+231" },
  { iso: "LY", nom: "Libye", indicatif: "+218" },
  { iso: "MG", nom: "Madagascar", indicatif: "+261" },
  { iso: "MW", nom: "Malawi", indicatif: "+265" },
  { iso: "ML", nom: "Mali", indicatif: "+223" },
  { iso: "MR", nom: "Mauritanie", indicatif: "+222" },
  { iso: "MU", nom: "Maurice", indicatif: "+230" },
  { iso: "MA", nom: "Maroc", indicatif: "+212" },
  { iso: "MZ", nom: "Mozambique", indicatif: "+258" },
  { iso: "NA", nom: "Namibie", indicatif: "+264" },
  { iso: "NE", nom: "Niger", indicatif: "+227" },
  { iso: "NG", nom: "Nigeria", indicatif: "+234" },
  { iso: "RW", nom: "Rwanda", indicatif: "+250" },
  { iso: "ST", nom: "Sao Tomé-et-Principe", indicatif: "+239" },
  { iso: "SN", nom: "Sénégal", indicatif: "+221" },
  { iso: "SC", nom: "Seychelles", indicatif: "+248" },
  { iso: "SL", nom: "Sierra Leone", indicatif: "+232" },
  { iso: "SO", nom: "Somalie", indicatif: "+252" },
  { iso: "ZA", nom: "Afrique du Sud", indicatif: "+27" },
  { iso: "SS", nom: "Soudan du Sud", indicatif: "+211" },
  { iso: "SD", nom: "Soudan", indicatif: "+249" },
  { iso: "TZ", nom: "Tanzanie", indicatif: "+255" },
  { iso: "TG", nom: "Togo", indicatif: "+228" },
  { iso: "TN", nom: "Tunisie", indicatif: "+216" },
  { iso: "UG", nom: "Ouganda", indicatif: "+256" },
  { iso: "ZM", nom: "Zambie", indicatif: "+260" },
  { iso: "ZW", nom: "Zimbabwe", indicatif: "+263" },
  // Reste du monde (diaspora + partenaires principaux)
  { iso: "FR", nom: "France", indicatif: "+33" },
  { iso: "BE", nom: "Belgique", indicatif: "+32" },
  { iso: "CH", nom: "Suisse", indicatif: "+41" },
  { iso: "CA", nom: "Canada", indicatif: "+1" },
  { iso: "US", nom: "États-Unis", indicatif: "+1" },
  { iso: "GB", nom: "Royaume-Uni", indicatif: "+44" },
  { iso: "DE", nom: "Allemagne", indicatif: "+49" },
  { iso: "ES", nom: "Espagne", indicatif: "+34" },
  { iso: "IT", nom: "Italie", indicatif: "+39" },
  { iso: "PT", nom: "Portugal", indicatif: "+351" },
  { iso: "NL", nom: "Pays-Bas", indicatif: "+31" },
  { iso: "CN", nom: "Chine", indicatif: "+86" },
  { iso: "IN", nom: "Inde", indicatif: "+91" },
  { iso: "AE", nom: "Émirats arabes unis", indicatif: "+971" },
  { iso: "SA", nom: "Arabie saoudite", indicatif: "+966" },
  { iso: "TR", nom: "Turquie", indicatif: "+90" },
  { iso: "BR", nom: "Brésil", indicatif: "+55" },
  { iso: "LB", nom: "Liban", indicatif: "+961" },
];
